### ISSUE TITLE
Manager issue: Cannot read property 'close' of undefined

### ISSUE THREAD

**Issue by LowieHuyghe** [edmundsjs/framework#256]
TypeError: Cannot read property 'close' of undefined
    at DatabaseManager.destroyConnection (.../edmunds/lib/database/databasemanager.ts:20:21)
    at DatabaseManager.BaseManager.destroy (.../edmunds/lib/support/basemanager.ts:238:12)
    at DatabaseManager.<anonymous> (.../edmunds/lib/support/basemanager.ts:181:18)
    at step (.../edmunds/dist/support/basemanager.js:32:23)
    at Object.next (.../edmunds/dist/support/basemanager.js:13:53)
    at .../edmunds/dist/support/basemanager.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (.../edmunds/dist/support/basemanager.js:3:12)
    at DatabaseManager.BaseManager.destroyAll (.../edmunds/dist/support/basemanager.js:119:16)
    at Edmunds.<anonymous> (.../edmunds/lib/edmunds.ts:142:13)

**Comment by LowieHuyghe** [comment]
Done
